site_name: ifctrano
site_description: IFC energy simulation tool with Modelica
repo_name: ifctrano
repo_url: https://github.com/andoludo/ifctrano
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/lightbulb-auto
        name: Switch to light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/lightbulb-outline
        name: Switch to system preference

  features:
  - content.code.annotate
  - content.code.copy
  # - content.code.select
  - content.footnote.tooltips
  - content.tabs.link
  - content.tooltips
  - navigation.footer
  - navigation.indexes
  - navigation.instant
  - navigation.instant.prefetch
  # - navigation.instant.preview
  - navigation.instant.progress
  - navigation.path
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.top
  - navigation.tracking
  - search.highlight
  - search.share
  - search.suggest
  - toc.follow

  icon:
    repo: fontawesome/brands/github-alt
  logo: img/ifctrano.webp
  favicon: img/ifctrano.webp
  language: en
plugins:
  - search
nav:
  - ifctrano: index.md
  - Getting-started:
    - Installation: getting-started/installation.md
  - Tutorials:
    - Two zones model: tutorials/two_zones_model.md
    - Use different libraries: tutorials/use_different_libraries.md
    - Many zones model: tutorials/many_zones_model.md
    - Realistic model: tutorials/realistic_model.md
  - How-to Guides: how-to guides/index.md
  - Explanation: explanation/index.md


markdown_extensions:
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - markdown_include.include:
        base_path: docs
    - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
